version: '3'
services:
  ingestion: # Not OK
    container_name: ingestion-app
    build: ingestion/.
    ports:
      - "5000:5000"
    working_dir: /app
    # depends_on:
    #   - postgres
    # environment:
    #   DATABASE_URL: postgres://username:password@postgres:5432/dbname
    networks:
      - main_network

  dectection: # Not OK
    image: python:3.8
    container_name: dection-yolo
    ports:
      - "8000:5000"
    working_dir: /dectection
    command: sh -c "pip install -r requirements.txt && python app.py"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://username:password@postgres:5432/main
    networks:
      - main_network
  
  minio: # Not OK
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - main_network
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_password
      - MINIO_DEFAULT_BUCKETS=storageone
      
  rabbitmq: # Not OK
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672" 
    networks:
      - main_network
      
  postgres: # OK
    image: postgres:12
    container_name: postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - main_network


volumes:
  pgdata:
  minio_data:
    driver: local
  

networks:
  main_network:
